### ISSUE TITLE
Cannot use rules sass in corporate network

### ISSUE THREAD

**Issue by KeshavRathi** [bazelbuild/rules_sass#104]
Hi,

The build system in the company I work in, does not have internet access for downloading libraries. We use internal artifactory for all the node libraries. yarn.lock file in this rules repo has all the url's pointing to internet.

yarn.lock location: https://github.com/bazelbuild/rules_sass/blob/master/sass/yarn.lock

Example:
"@bazel/worker@latest":
  version "0.37.0"
  resolved "https://registry.yarnpkg.com/@bazel/worker/-/worker-0.37.0.tgz#36354ba28389e9e0ebf03ec2a9cbf4e7b02d5cba"
  integrity sha512-uEXbehz5dcO/LErfjIx0I2nmmiWWeK0pOeMPFYpMx7oiuFxEIF0porTsJL5Y5kTHP5/6U15in04IDWn/QJdQUw==
  dependencies:
    protobufjs "6.8.8"

Is there a way to forward these requests to corporate network? If not, Please provide a support for using **registry.corporate.com** instead of **registry.yarnpkg.com**.

Thank you.

**Comment by yoonjesung** [comment]
So, you should be able to pass in a .rc file (npmrc or yarnrc) into the data attribute and set the registry in the rc file. However, I haven't been able to get this feature to work. If you're able to get that working please do share.

**Comment by nex3** [comment]
@alexeagle What's the standard practice for this sort of thing?

**Comment by KeshavRathi** [comment]
@yoonjesung I tried adding .yarnrc in my base directory of the UI project. Seems like the registry property is not proxying rules_sass yarn.lock.

Also tried https://medium.com/@crysfel/using-different-registries-in-yarn-and-npm-766541d6f851 for proxying requests.

Can you please share what was the content of the data attribute of yarn_install which you used?

**Comment by yoonjesung** [comment]
@KeshavRathi Sorry, to be more clear, I was not able to get the data attribute to process an rc file with registry properly. I went the route of `symlink_node_modules = true` and then made the node_modules generated by yarn managed by the workspace -- if you go this route you'll have to set `common --experimental_allow_incremental_repository_updates` in .bazelrc

**Comment by alexeagle** [comment]
Just noticed my assignment here.

I think the answer is simple: the `sass_repositories` helper function is just there to create a repo containing two dependencies. You can just inline that function into your WORKSPACE and call it with whatever arguments you like.

In rules_nodejs we have moved to having rules distributed along with npm packages, without any install steps in the WORKSPACE file. This way the only npm/yarn install step is the user-managed one. That might be a direction to take rules_sass as well.
