### ISSUE TITLE
Please move from native to Skylark rules for external git/http repositories

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/rules_sass#27]
Bazel is planning to move away from native rules for external repositories to Skylark rules, mainly because bundling every version control system in bazel does not scale. As part of this effort, we plan to submit https://bazel-review.googlesource.com/c/bazel/+/55932 soon, which will cause bazel by default to insist that the skylark versions the git and http rules for external repositories be used. This can be disabled by a flag for at least the next 6 months, but we still would appreciate if you could adopt your repository to use the Skylark versions of those rules soon.

A test run of downstream projects with that flag flip in bazel enabled can be found at https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/286

For more background, see
- the original announcement https://groups.google.com/d/topic/bazel-discuss/dO2MHQLwJF0/discussion
- and the documentation of the incompatible changes https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#remove-native-git-repository

Thanks.

**Comment by nex3** [comment]
As of #26, this package no longer supports LibSass, which is what it's using the native rules for. I believe @jelbourn will be putting out a CL to get rid of the native rules entirely soon.

**Comment by nex3** [comment]
I believe this is fixed now.

**Comment by mhlopko** [comment]
I don't think this is fixed: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/531#f77e7d50-a1cd-4f84-a022-cab4136aa176. Please fix quickly and create an issue at bazelbuild/continuous-integration to reenable. Keep in mind that we are not catching unintentional breakages of this project in bazel@HEAD.

**Comment by jelbourn** [comment]
@mhlopko this _has_ been fixed in this repo, but the target you linked is still failing because skydoc has not been updated
* https://github.com/bazelbuild/skydoc/blob/master/WORKSPACE#L21
* https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/531#63c539ff-9bca-4117-8e88-8ff6cc920195

I've sent a PR to the skydoc repo: https://github.com/bazelbuild/skydoc/pull/113

**Comment by jelbourn** [comment]
Filed https://github.com/bazelbuild/continuous-integration/issues/363

**Comment by mhlopko** [comment]
Thank you so much! Did you update the skydoc version in your workspace?

**Comment by jelbourn** [comment]
It's in https://github.com/bazelbuild/rules_sass/pull/55, should be merged shortly

**Comment by jelbourn** [comment]
It looks like a recent commit in skydoc (https://github.com/bazelbuild/skydoc/commit/8632e30e7b1fa2d58f73ea0ef1f043b4b35794f5) broke consuming it via `http_archive`. I'll debug this tomorrow since I'm travelling today.

**Comment by jelbourn** [comment]
Skydoc version has been bumped.

**Comment by meteorcloudy** [comment]
@jelbourn Can you bump skydoc version to https://github.com/bazelbuild/skydoc/commit/77e5399258f6d91417d23634fce97d73b40cf337 ?
