### ISSUE TITLE
Keep the Dart Sass version up to date automatically

### ISSUE THREAD

**Issue by nex3** [bazelbuild/rules_sass#28]
Dart Sass releases frequently, and it would be good not to require a human to update the dependency in this repo with every release. I could add support to the Dart Sass release process to automatically update [the `package.json` file](https://github.com/bazelbuild/rules_sass/blob/master/sass/package.json), but in order to do that I need Sass's automation account @sassbot to be given commit access to this repository.

**Comment by dslomov** [comment]
@alexeagle @davidzchen @perezd Is that something we should allow?

**Comment by alexeagle** [comment]
Yes, that sounds like great automation. I think we should also consider how to tag this repo so that users can actually pick up the change - the simplest scheme would be for rules_sass version to match dart_sass ?

**Comment by nex3** [comment]
> the simplest scheme would be for rules_sass version to match dart_sass 

This would also be the easiest for me to automate.

**Comment by dslomov** [comment]
Added @sassbot

**Comment by nex3** [comment]
It looks like @sassbot still doesn't have write permissions; [the Travis job](https://travis-ci.org/sass/dart-sass/jobs/394359834)'s `git push` command is failing with

```
  remote: Permission to bazelbuild/rules_sass.git denied to sassbot.
  fatal: unable to access 'https://sassbot:[secure]@github.com/bazelbuild/rules_sass.git/': The requested URL returned error: 403
```

**Comment by nex3** [comment]
This is working as of https://github.com/sass/dart-sass/commit/5ca8ba35197b46cc7dd83eea7accfe7efc86a6b9.

**Comment by alexeagle** [comment]
Cool, but one nit, it would be nice to have some sort of changelog included
with the release notes like at
https://github.com/bazelbuild/rules_sass/releases/tag/1.9.0

**Comment by nex3** [comment]
What sort of changelog are you envisioning? It would have to be something that can be auto-generated or scraped.

**Comment by alexeagle** [comment]
Yeah the simplest thing would be to list the commits in the release with
links to the PRs. For Angular we use
https://github.com/conventional-changelog/conventional-changelog which also
uses some conventions about commit descriptions to group the changes, and
calls out any with BREAKING CHANGE in the description.
Jeremy did the nice release notes last time, maybe he has some opinions.

Another option would just be to put some canned text in the tag description
like "this is based on commits in [other repo], go look at the changes
there"

**Comment by nex3** [comment]
If we use something like `conventional-changelog`, maybe it would make sense to run it as part of this repo's CI? That way if a release needs to be cut independently of Dart Sass, the release notes would still be generated.

**Comment by alexeagle** [comment]
Eh, feels like a lot more work and maintenance than it's worth. I don't
feel strongly about it.
