### ISSUE TITLE
sass rule with multiple sources

### ISSUE THREAD

**Issue by kyliau** [bazelbuild/rules_sass#72]
There had been some discussion around the need for a rule that accepts a list of sources.

Previous [discussion](https://github.com/bazelbuild/rules_sass/issues/22) resulted in https://github.com/bazelbuild/rules_sass/pull/23 being merged but the change was reverted in https://github.com/bazelbuild/rules_sass/pull/26.

In many cases, the single input single output rule is the logical way things should be structured.
However, in some cases, it is also desirable to allow some flexibility by accepting a list of sources.
A helpful example was presented in https://github.com/bazelbuild/rules_sass/issues/22#issuecomment-385030909. 
For Angular, it is also especially useful to `@angular/bazel` schematics where BUILD files and rules are automatically generated, and Bazel implementation is hidden from the user as much as possible. In the first iteration of the schematics, there is only a single build rule for the entire project.

Without a rule like `multi_sass_binary`, it is not possible for `@angular/bazel` to generate a target that would work with different repository layouts.

A promising [solution](https://github.com/bazelbuild/rules_sass/pull/66) is to use a gazelle plugin to automatically generate the right library and binary targets. However, the PR is still in works, and more importantly, gazelle would also automatically generate BUILD files for each directory, which breaks the one rule policy of `@angular/bazel`.

We've tried composing multiple `sass_binary` rules with list comprehension, but this approach breaks down when one file imports from other files.

So, what's the general consensus on this? Should we implement a rule similar to `multi_sass_binary` outside of `rules_sass`, or should it be reinstated here?

Thank you!

**Comment by alexeagle** [comment]
From #26, my comment:

> "We are not sure how the multi_sass_binary fits in with our internal Sass story, and our objective here is to make these the same. So if we adopt multi_sass_binary, we would want to allow usage internally at Google also."

IIRC we would have liked to keep `multi_sass_binary` but it was just too difficult to re-implement at the time.

**Comment by nex3** [comment]
My recollection is that we decided that a multi-input rule was too messy, in the sense that most of the time each input stylesheet only imported a subset of the rule's deps, so it would cause extra unnecessary recompilation when an upstream dep changed. This could also become a more serious issue if and when we add strict checking to the rules to ensure that only imported files are listed in deps.
