### ISSUE TITLE
--incompatible_depset_is_not_iterable

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_sass#79]
rules_sass doesn't work with Bazel flag `--incompatible_depset_is_not_iterable`.

Result from the CI: https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/30#1e6dce1f-3a42-4eb4-88b7-f06f1cdcab7a

```
File "/var/lib/buildkite-agent/builds/bk-docker-5c9v/bazel-downstream-projects/rules_sass/sass/sass.bzl", line 232, in depset
  [f for t in ctx.attr.srcs for f in t.files]
  type 'depset' is not iterable. Use the `to_list()` method to get a list. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
```

Related documentation: https://docs.bazel.build/versions/master/skylark/depsets.html

Could you take a look at this?

**Comment by nex3** [comment]
Alex, can you take a look at this? It's out of my skylark depth.
